version: '3.1'

services:
  backend:
    build: .
    environment:
      MONGO_DSN: "mongodb://beanie:beanie@mongodb:27017/beanie_db"
    ports:
      - 8010:8000

  mongodb:
    image: bitnami/mongodb:latest
    environment:
      MONGODB_ROOT_PASSWORD: root
      MONGODB_USERNAME: beanie
      MONGODB_PASSWORD: beanie
      MONGODB_DATABASE: beanie_db
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

volumes:
  mongodb: